---
title: "R Notebook"
output: html_notebook
---

```{r}
library(readxl)
library(xtable)
```
```{r}
#import plikow
dane <- read_xlsx('dane/gospodarstwa.xlsx', sheet = 1)
zmienne <- read_xlsx('dane/gospodarstwa.xlsx', sheet = 2, range = 'A2:B18')
etykiety <- read_xlsx('dane/gospodarstwa.xlsx', sheet = 3, range = 'A2:C70')
```
```{r}
library(dplyr)
library(xtable)
```
```{r}
# Zadanie 2. Utwórz zbiór, w którym są gospodarstwa ze wsi.
# %>%

zad2 <- dane[dane$klm==6,]
zad2dpl <- dane %>% filter(klm==6)
zad2dpl
identical(zad2,zad2dpl)
```
```{r}
# Zadanie 3. Utwórz zbiór, w którym są gospodarstwa o dochodach > 2000 zł.

zad3 <- dane[dane$dochg>2000,]
zad3dpl <- dane %>% filter(dochg>2000 | is.na(dochg))
zad3dpl
identical(zad3,zad3dpl)
```
```{r}
# Zadanie 4. Utwórz zbiór, który zawiera gospodarstwa z województwa wielkopolskiego oraz które zamieszkują wieś i mają dochody powyżej 3000 zł.

zad4 <- dane %>% filter(woj=='30' & klm==6 & dochg>3000)
zad4
```

```{r}
# Zadanie 5. Wybierz gospodarstwa domowe z województwa dolnośląskiego i mazowieckiego z miast powyżej 500 tys. mieszkańców.

zad5 <- dane %>% filter(woj%in% c('02','14') & klm==1)
zad5
```

```{r}
# Zadanie 6. Losowo wybierz zbiór 30% gospodarstw domowych
set.seed(1)
zad6 <- dane %>% slice_sample(prop = 0.3, replace = FALSE)
zad6
```

```{r}
## Zagraj w totolotka
toto <- as.data.frame(1:49)
toto %>% slice_sample(n=6, replace = FALSE)
```

```{r}
# Zadanie 7. Losowo wybierz 100 gospodarstw

zad7 <- dane %>% slice_sample(n=100, replace = FALSE)
zad7
```
```{r}
# Zadanie 8. Wybierz gospodarstwa domowe z wierszy 10–15.

zad8 <- dane %>% slice(10:15)
zad8
```

```{r}
# Zadanie 9. Wybierz gospodarstwa domowe z danymi tylko dla kolumny woj i wydg
# ale w odniesieniu jedynie dla gospodarstw z województwa wielkopolskiego.

zad9 <- dane %>% filter(woj=='30') %>%
                 select(woj,wydg)
zad9
```

```{r}
# Zadanie 10. Wybierz wszystkie gospodarstwa, których dochód jest z przedziału
# 3000–4000 i zostaw tylko tą zmienną w zbiorze.

zad10 <- dane %>% filter(between(dochg, 3000, 4000)) %>% select(dochg)
zad10
```

```{r}
# Zadanie 11. Wybierz wszystkie kolumny od klm do zut włącznie.

zad11 <- dane %>% select(klm:zut)
zad11
```
```{r}
# Zadanie 12. Wyświetl nazwy wszystkich zmiennych w zbiorze gospodarstwa.
names(dane)
```

```{r}
# Zadanie 13. Wybierz wszystkie kolumny, które zaczynają się na literę d

zad13 <- dane %>% select(starts_with('d'))
zad13
```

```{r}
# Zadanie 14. Utwórz nową zmienną roznica=dochg-wydg. Pozostaw w zbiorze zmienne
# dochg, wydg i roznica.

zad14 <- dane %>% mutate(roznica=dochg-wydg) %>%
                  select(dochg,wydg,roznica)
zad14
```

```{r}
# Zadanie 15. Utwórz nowe zmienne x=ln(dochg) oraz y=ln(wydg). Pamiętaj, że ln
# liczymy dla dodatnich wartości.

zad15 <- dane %>% filter(dochg>0 & wydg>0) %>%  
                  mutate(x=log(dochg), y=log(wydg))
zad15
```
```{r}
#praca domowa
# wybierz gospodarstwa z woj kuj-pom zamieszkujące wieś. Utworz zmienna doch5, ktora jest o 5% wieksza od dochg (weź dochody dodatnie). Zostaw zmienne: woj, dochg, doch5.

zaddom <- dane %>% filter(woj=='04') %>% filter(klm==6) %>% filter(dochg>0) %>%
                   mutate(doch5 = dochg*1.05) %>% select(woj,dochg,doch5)
zaddom
```
```{r}
# Zadanie 16. Dokonaj zamiany nazwy zmiennych dochg na dochod oraz wydg na
# wydatki.

zad16 <- dane %>% rename(dochod=dochg, wydatki=wydg)
zad16
```
```{r}
# Zadanie 17. Oblicz ile było gospodarstw domowych ze względu na poszczególne
# warianty zmiennej klm.

zad17a <- dane %>% group_by(klm) %>% count()
zad17a
# xtable(zad17a)

zad17b <- dane %>% count(klm)


```

```{r}
# Zadanie 20. Oblicz średnie wydatki wszystkich gospodarstw domowych

zad20 <- dane %>% summarise(srednia=mean(wydg, na.rm=TRUE))
zad20
```
```{r}
# Zadanie 21. Oblicz średnie wydatki i dochody wszystkich gospodarstw domowych

zad21 <- dane %>% filter(dochg>0) %>% summarise(srednia_wyd=mean(wydg,na.rm=TRUE), srednia_dochg=mean(dochg,na.rm=TRUE))
zad21
```

```{r}
# Zadanie 22. Oblicz średnią, min, max, odchylenie standardowe oraz medianę wydatków.

zad22 <- dane %>% summarise(srednia=mean(wydg, na.rm=TRUE), minimum=min(wydg, na.rm=TRUE), maximum=max(wydg, na.rm=TRUE), odchylenie=sd(wydg, na.rm=TRUE), mediana=median(wydg, na.rm=TRUE))
zad22
```

```{r}
# Zadanie 23. Oblicz średnie wydatki w ramach klasy miejscowości.

zad23 <- dane %>% group_by(klm) %>% summarise(srednia=round(mean(wydg, na.rm=TRUE),1))
zad23
```

```{r}
# Zadanie 25. Posortuj rosnąco zbiór gospodarstw domowych ze względu na wydatki

zad25 <- dane %>% arrange(wydg)
zad25
```
```{r}
# Zadanie 26. Posortuj malejąco zbiór gospodarstw domowych ze względu na dochody.

zad26 <- dane %>% arrange(-dochg)
zad26
```
```{r}
# Zadanie 27. Posortuj malejąco kod klasy miejscowości a w ramach tej klasy rosnąco
# wydatki.

zad27 <- dane %>% arrange((-klm),wydg)
zad27
```
```{r}
# Zadanie 32. Utwórz nową zmienną „klasa”, która przyjmuje dwie wartości: „wieś”,
# gdy gospodarstwo jest ze wsi oraz „miasto”, gdy gospodarstwo jest z miasta.

zad32 <- dane %>% mutate(klasa=case_when(klm==6 ~ 'wies' , TRUE ~ 'miasto'))
barplot((table(zad32$klasa)))
zad32
```
```{r}

# Zadanie 33. Utwórz nową zmienną „pow”, która przyjmuje trzy warianty: „do 60”,
# „(60-100>” oraz „powyżej 100” w zależności od wartości zmiennej d36 (powierzchnia
# mieszkań).

zad33 <- dane %>% mutate(pow=case_when(d36<=60 ~ '   do 60' , d36<=100 ~ '  60-100', TRUE ~ ' powyzej 100'))
barplot(table(zad33$pow))
table(zad33$pow)
```
```{r}
zad34 <- dane %>% mutate(dochod=case_when(is.na(dochg) ~ 'brak danych', dochg <= 2000 ~ 'niski', dochg <= 5000 ~ 'sredni', TRUE ~ 'wysoki'))
table(zad34$dochod)
```
```{r}
# Zadanie 30. Utwórz zbiór wlkp. W zbiorze tym powinny się znaleźć gospodarstwa
# z województwa wielkopolskiego, których dochód jest z przedziału 2500–3000 zł. Dochód powinien być posortowany malejąco. Oprócz dochodu mają się znaleźć 4 inne
# zmienne: klm, woj, zut i wydg. Na tym zbiorze, dla zmiennych dochg i wydg, stwórz
# korelacyjny diagram rozrzutu.

zad30 <- dane %>% filter(woj=='30' & between(dochg,2500,3000)) %>% arrange(-dochg) %>% select(klm,woj,zut,wydg,dochg)
plot(zad30$dochg, zad30$wydg, xlab = 'dochody' , ylab = 'wydatki', col = 'blue', main = 'korelacyjny diagram rozrzutu',
     pch = 19)
zad30

```
```{r}
##
##zad18 i zad19 i zad31
##
```
```{r}
# Zadanie 18. Oblicz ile było gospodarstw domowych w poszczególnych województwach.

zad18 <- dane %>% group_by(woj) %>% count()
zad18
```
```{r}
zad19 <- dane %>%  count(d61)
zad19
```

```{r}
zad31 <- dane %>% mutate(roznica = dochg - wydg, doch_os = dochg/los) %>% select(roznica,doch_os)
zad31
```
```{r}
#Oblicz srednia i mediane powierzchni w przekroju wojewodztw i wygeneruj kod latexowy do tabeli

tabela <- dane %>% group_by(woj) %>% summarise(srednia=mean(d36, na.rm=TRUE))
xtable(tabela)
                                              


```