---
title: "R Notebook"
output: html_notebook
---

```{r}
#metoda topsis w programie R - ujecie macierzowe
library(readxl)
library(dplyr)
library(tmap)
library(tmaptools)
library(sf)
library(rgdal)
library(topsis)
library(ggplot2)
```

```{r}
#wczytujemy dane z pliku powiaty.xlsx

powiaty <- read_xlsx('dane/Powiaty.xlsx', sheet = 1)

etykiety <- read_xlsx('dane/Powiaty.xlsx', sheet = 2)

powiaty$JPT_KOD_JE <- as.character(powiaty$JPT_KOD_JE)

```

```{r}
#utworzenie znormalizowanej macierzy danych zij

xij <- powiaty %>% select(3:8) %>% as.matrix()
print(xij)

zij <- matrix(,nrow(xij), ncol(xij))
print(zij)

for(j in 1:6){
  zij[,j] <- round(xij[,j]/sqrt(sum(xij[,j]^2)),2)
}
print(zij)
```

```{r}
# tworzymy wagi wj

wj <- rep(1,6)
print(wj)

vij <- wj*zij
print(vij)
```
```{r}
# tworzymy wektor a+ i a-

apl <- c(max(vij[,1]),max(vij[,2]),min(vij[,3]),min(vij[,4]),min(vij[,5]),min(vij[,6]))
ami <- c(min(vij[,1]),min(vij[,2]),max(vij[,3]),max(vij[,4]),max(vij[,5]),max(vij[,6]))
print(apl)
print(ami)
```

```{r}
# oblicznie odleglosci euklidesowych badanych obiektow od rozwiazania idealnego i antyidealnego

dpl <- matrix(,nrow(xij),1)
dmi <- matrix(,nrow(xij),1)

for(i in 1:nrow(xij)){
  dpl[i,1] <- sqrt(sum((vij[i,]-apl)^2))
  dmi[i,1] <- sqrt(sum((vij[i,]-ami)^2))
}
print(dpl)
print(dmi)
```

```{r}
# wyznaczenie wspolczynnika rankingowego okreslajacego podobienstwo obiektow do rozwiazania idealnego

R <- round(dmi/(dmi+dpl),2)
print(R)

powiaty$R <- as.vector(R)
```

```{r}
# robimy to samo pakietem topsis

i <- c('+','+','-','-','-','-')
R1 <- topsis(xij,wj,i)
print(R1)
powiaty$R1 <- R1
```
```{r}
# tworzymy wykres z rankingiem

powiaty %>% arrange(R) %>%
ggplot(aes(x=factor(Powiaty,levels=Powiaty),y=R)) +
geom_point(stat='identity',size=4)+
coord_flip() +
theme_bw()+
geom_segment(aes(y=0,x=Powiaty,yend=R,xend=Powiaty))+
labs(y='R',x='Powiaty')
```

```{r}

```

```{r}
# tworzymy kartogram z miara R dla powiatow woj wlkp

powiaty1 <- st_read('Powiaty/Powiaty.shp')

powiaty.wlkp <- powiaty1[substr(powiaty1$JPT_KOD_JE,1,2)=='30',]

data_all_wlkp <- left_join(powiaty.wlkp,powiaty)

tm_shape(data_all_wlkp) +
tm_polygons('R',border.col='black',title='Topsis',
breaks=quantile(data_all_wlkp$R)) +
tm_text('Powiaty', size=0.7) +
tm_shape(data_all_wlkp)+
tm_text('R', size=0.7,ymod=-0.5)
```

```{r}
dist.wlkp.eucl <- dist(powiaty[,3:8],method='euclidean')
cluster <- hclust(dist.wlkp.eucl,method='ward.D')
plot(cluster,labels=powiaty$Powiaty)
rect.hclust(cluster,k=4,border='blue')

pow.cluster <- cutree(cluster,k=4)
# print(pow.cluster)
powiaty$cluster <- pow.cluster

data_all_wlkp <- left_join(powiaty.wlkp,powiaty)

tm_shape(data_all_wlkp) +
tm_polygons('cluster',border.col='black',title='Cluster') +
tm_text('Powiaty', size=0.7) +
tm_shape(data_all_wlkp)+
tm_text('cluster', size=0.7,ymod=-0.5)
```